# Autoencoder config for MELO-GAN
MAX_NOTES: 512
LATENT_DIM: 8
BATCH_SIZE: 32
LR: 0.0001
EPOCHS: 100 #60
WEIGHT_DECAY: 0.00001
KLD_WARMUP_EPOCHS: 1
BETA: 10.0                 # <--- ADD THIS. This will multiply KLD loss by 5.
EARLY_STOP_PATIENCE: 15

# augmentation settings
AUGMENT:                  # <--- We are reducing all of these
  tempo_jitter: 0.0      # (was 0.07)
  pitch_shift: 0          # (was 1)
  note_dropout: 0.0     # (was 0.03)
  velocity_jitter: 0.0    # (was 8.0)
  timing_jitter: 0.0     # (was 0.02)

# directories
PROCESSED_DIR: data/processed
SPLITS_DIR: data/splits
CHECKPOINT_DIR: data/models/ae
LOG_DIR: experiments/ae
RECON_DIR: experiments/ae/reconstructions
RECON_FREQ: 1
RECON_SAVE_COUNT: 6
